config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'transactions#index'
  resources :transfers
  resources :customers
  resources :transactions, :path => "/"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!

  # GET /customers
  # GET /customers.json
  def index
    @customers = Stripe::Customer.all(:limit => 100)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show]
  before_action :authenticate_user!

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Stripe::BalanceTransaction.all(:limit => 20)
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Stripe::Charge.retrieve(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params[:transaction]
    end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!
  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Stripe::Transfer.all(:limit => 20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="field">
    <%= f.label :show %><br>
    <%= f.text_field :show %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>created</th>
      <th>id</th>
      <th>email</th>
      <th>description</th>
      <th>metadata</th>
      <th>payment method</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= Time.at(customer['created']).to_datetime %></td>
        <td><%= customer['id'] %></td>
        <td><%= customer['email'] %></td>
        <td><%= customer['description'] %></td>
        <td><%= customer['metadata'] %></td>
        <% if customer['sources']['data'][0].nil? %>
        <td>No credit card</td>
        <% else %>
        <td><%= customer['sources']['data'][0]['object'] %></td>
        <td><%= customer['sources']['data'][0]['brand'] %></td>
        <td><%= customer['sources']['data'][0]['last4'] %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stripe" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Stripe QA Page</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-left">
          <li><a href="/">Transactions</a></li>
          <li><a href="/transfers/">Transfers</a></li>
          <li><a href="/customers/">Customers</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
            </div>
          </ul>
      </div>
    </div>

    <div class="container">
      <div>
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Wetravel.to 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recent Transactions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>Created at</td>
        <td>Amount</td>
        <td>Currency</td>
        <td>Status</td>
        <td>Transaction ID</td>
        <td></td>
      </tr>
      <% @transactions.data.each do |transaction| %>
      <tr>
        <td><%= Time.at(transaction['created']).to_datetime %></td>
        <td><%=  transaction['amount'] / 100 %></td>
        <td><%=  transaction['currency'] %></td>
        <td><%=  transaction['status'] %></td>
        <td><%=  transaction['source'] %></td>
        <td><%= link_to 'Show', transaction['source'], :class => 'btn btn-primary btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Transaction Details</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <tr>
        <% if @transaction.id.start_with?("ch_") %>
			<td>Id</td>
			<td>Amount</td>
			<td>Currency</td>
			<td>Status</td>
			<td>Refunded</td>
			<td>Captured</td>
			<td>Object</td>
			<td>Last4</td>
			<td>Brand</td>
			<td>Metadata</td>
		<% else %>
			<td>Id</td>
			<td>Amount</td>
			<td>Currency</td>
			<td>Status</td>
			<td>Refunded</td>
			<td>Captured</td>
			<td>Object</td>
			<td>Last4</td>
			<td>Bank</td>
			<td>Metadata</td>
		<% end %>
      </tr>
      <tr>
        <% if @transaction.id.start_with?("ch_") %>
			<td><%= @transaction.id %> </td>
			<td><%= @transaction.amount %> </td>
			<td><%= @transaction.currency %> </td>
			<td><%= @transaction.status %> </td>
			<td><%= @transaction.refunded %> </td>
			<td><%= @transaction.captured %> </td>
			<td><%= @transaction.source.object %> </td>
			<td><%= @transaction.source.last4 %> </td>
			<td><%= @transaction.source.brand %> </td>
			<td><%= @transaction.metadata %> </td>
		<% else %>
			<td><%= @transaction.id %> </td>
			<td><%= @transaction.amount %> </td>
			<td><%= @transaction.currency %> </td>
			<td><%= @transaction.status %> </td>
			<td><%= @transaction.refunded %> </td>
			<td><%= @transaction.captured %> </td>
			<td><%= @transaction.source.object %> </td>
			<td><%= @transaction.source.last4 %> </td>
			<td><%= @transaction.source.bank_name %> </td>
			<td><%= @transaction.metadata %> </td>
		<% end %>
      </tr>
  </tbody>
</table>

<%= link_to 'Back', transactions_path %>

app/views/transfers/_form.html.erb
<%= form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="field">
    <%= f.label :show %><br>
    <%= f.text_field :show %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>created</th>
      <th>amount</th>
      <th>currency</th>
      <th>status</th>
      <th>type</th>
      <th>description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= Time.at(transfer['created']).to_datetime %></td>
        <td><%= transfer['amount'] / 100 %></td>
        <td><%= transfer['currency'] %></td>
        <td><%= transfer['status'] %></td>
        <td><%= transfer['type'] %></td>
        <td><%= transfer['description'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>